In [84]:
import numpy as np
import time
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
from plotting import newfig, savefig
from torch.optim.lr_scheduler import StepLR
from scipy.special import comb
from scipy.stats import norm
from IPython.display import display, clear_output
from torch.distributions.normal import Normal



def theoretical_vanilla_eu_tensor_ver(S0=50, K=50, T=1, r=0.05, sigma=0.4, type_='call'):

    if T == 0:
        if type_ == "call":
            a = torch.clamp(S0 - K, 0)

            return a
        else:
            b = torch.clamp(K - S0, 0)

            return b
    # 求BSM模型下的欧式期权的理论定价
    d1 = ((torch.log(torch.tensor(S0 / K)) + (r + 0.5 * sigma ** 2) * T)) / (sigma * torch.sqrt(torch.tensor(T)))
    d2 = d1 - sigma * torch.sqrt(torch.tensor(T))
    m = Normal(torch.tensor([0.0]),torch.tensor([1.0]))
    if type_ == "call":
        c = S0 * m.cdf(d1) - K * torch.exp(torch.tensor(-r * T)) * m.cdf(d2)
        cc = torch.tensor(c, dtype=torch.float32)
        cc.requires_grad = True
        return cc
    elif type_ == "put":
        p = K * torch.exp(torch.tensor(-r * T)) * m.cdf(-d2) - S0 * m.cdf(-d1)
        pp = torch.tensor(p, dtype=torch.float32)
        pp.requires_grad = True
        return pp


In [85]:
print(theoretical_vanilla_eu_tensor_ver())

tensor([9.0115], requires_grad=True)


C:\Users\Haoya\AppData\Local\Temp\ipykernel_7556\353026849.py:33: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  cc = torch.tensor(c, dtype=torch.float32)


In [86]:

S0S = torch.tensor([50,50,50,50,0]).float()
S0S.requires_grad = True


In [87]:
print(theoretical_vanilla_eu_tensor_ver(S0S,50,1,0.05,0.4,'call'))

tensor([9.0115, 9.0115, 9.0115, 9.0115, 0.0000], requires_grad=True)


C:\Users\Haoya\AppData\Local\Temp\ipykernel_7556\353026849.py:28: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  d1 = ((torch.log(torch.tensor(S0 / K)) + (r + 0.5 * sigma ** 2) * T)) / (sigma * torch.sqrt(torch.tensor(T)))
C:\Users\Haoya\AppData\Local\Temp\ipykernel_7556\353026849.py:33: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  cc = torch.tensor(c, dtype=torch.float32)


In [92]:
S0S2 = torch.tensor([40,40,40,40]).unsqueeze(-1)
theoretical_vanilla_eu_tensor_ver(S0S2,40,1,0.05,0.4)

C:\Users\Haoya\AppData\Local\Temp\ipykernel_7556\353026849.py:28: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  d1 = ((torch.log(torch.tensor(S0 / K)) + (r + 0.5 * sigma ** 2) * T)) / (sigma * torch.sqrt(torch.tensor(T)))
C:\Users\Haoya\AppData\Local\Temp\ipykernel_7556\353026849.py:33: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  cc = torch.tensor(c, dtype=torch.float32)


tensor([[7.2092],
        [7.2092],
        [7.2092],
        [7.2092]], requires_grad=True)